export const ROLES = {
  ADMIN: 'ADMIN',
  ACCOUNTS: 'ACCOUNTS',
  DEPT_HEAD: 'DEPT HEAD',
  ERP: 'ERP',
  MAINTENANCE: 'MAINTENANCE',
  MANAGER: 'MANAGER',
  OPERATOR: 'OPERATOR',
  PRODUCTION: 'PRODUCTION',
  PRODUCTION_SERVICE_HEAD: 'PRODUCTION - SERVICE HEAD',
  PURCHASE: 'PURCHASE',
  QUALITY: 'QUALITY',
  QUOTATION_DEPARTMENT: 'Quotation Department',
  SPARES: 'SPARES',
  STORE: 'STORE',
  STORE_HEAD: 'STORE HEAD',
  STORE_MATERIAL_ISSUE: 'STORE MATERIAL ISSUE',
  SUPERVISOR: 'SUPERVISOR',
  TECHNICAL: 'TECHNICAL',
  TECHNICAL_HEAD: 'TECHNICAL HEAD'
};

export const STATUS = {
  ACTIVE: 'Active',
  INACTIVE: 'Inactive'
};

export const PAGE_SIZES = [5, 10, 25, 50];
